import { Inter } from 'next/font/google'
import '@/devlink/global.css'
import { DevLinkProvider } from '@/devlink/DevLinkProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DevLinkProvider>{children}</DevLinkProvider>
      </body>
    </html>
  )
}
